#name: vpn

services:
    ezy_ton_laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ezy_ton_laravel
        image: ezy_ton_laravel:latest
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - storage:/var/www/html/storage
        networks:
            - net

    ezy_ton_nginx:
        image: nginx
        container_name: ezy_ton_nginx
        working_dir: /var/www/html
        restart: unless-stopped
        ports:
            - "43224:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
            - storage:/var/www/html/storage
        networks:
            - net
        depends_on:
            - ezy_ton_laravel

#mysql:8.0-debian
    ezy_ton_mysql:
        image: mysql:latest
        container_name: ezy_ton_mysql
        restart: unless-stopped
        command: --max_allowed_packet=512M
        ports:
            - "3306:3306"
        environment:
#            MYSQL_ROOT_USER: root
            MYSQL_USER: omid
            MYSQL_ROOT_PASSWORD: Omid@1380
            MYSQL_DATABASE: ezy_ton_vpn
            MYSQL_PASSWORD: Omid@1380
        volumes:
            - db:/var/lib/mysql
        networks:
            - net

    # phpMyAdmin
    ezy_ton_phpmyadmin:
        image: phpmyadmin:latest
        container_name: ezy_ton_phpmyadmin
        restart: unless-stopped
        ports:
            - "34563:80"
        environment:
            PMA_HOST: ezy_ton_mysql
            MYSQL_ROOT_PASSWORD: Omid@1380
            UPLOAD_LIMIT: 500M
        networks:
            - net
        depends_on:
            - ezy_ton_mysql

volumes:
    storage:
        driver: local
    db:

networks:
    net:
        driver: bridge
